[build]
  base    = "front-end"      # your front-end folder
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"  # Ensure devDependencies get installed

[context.production.environment]
  NODE_ENV = "production"
